micronaut:
  security:
      enabled: true
      
akhq:
  connections:
    cluster-sasl:
      properties:
        bootstrap.servers: "kafka:9092"
  
  security:
    default-group: no-roles
    basic-auth:
      - username: admin
        password: 9b8769a4a742959a2d0298c36fb70623f2dfacda8436237df08d8dfd5b37374c # must be SHA256 
        groups:
          - admin